// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aewmtsqhydzqunnghjtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFld210c3FoeWR6cXVubmdoanR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NDU1OTYsImV4cCI6MjA3NjAyMTU5Nn0.3DjvGC15K014rtVowlgUvNdXg9KSZq-y_Lhf-8yI88Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});