// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eurylsxxtikbbofcmrhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1cnlsc3h4dGlrYmJvZmNtcmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2Mjc5NzUsImV4cCI6MjA4OTIwMzk3NX0.b4QRJhxWhHSJy9F0bcJqlyX77xGznSjKflBzt23y0oI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});